resolucion ejercicio de los hospitales

In [2]:
import numpy as np
import pandas as pd

In [3]:
df_hospitales = pd.read_csv('hospitales2.csv',sep=',',decimal='.')

In [4]:
df_hospitales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 20 columns):
WKT           36 non-null object
ID            36 non-null float64
NOMBRE        36 non-null object
NOM_MAP       36 non-null object
OBJETO        36 non-null object
CALLE         36 non-null object
ALTURA        36 non-null int64
DOM_NORMA     36 non-null object
DOM_GEO       36 non-null object
TELEFONO      36 non-null object
GUARDIA       34 non-null object
FAX           35 non-null object
WEB           13 non-null object
COD_POSTAL    36 non-null object
TIPO          36 non-null object
TIPO_ESPEC    35 non-null object
MOD_AT_1      35 non-null object
MOD_AT_2      35 non-null object
DEPEND_ADM    36 non-null object
DIRECTOR      36 non-null object
dtypes: float64(1), int64(1), object(18)
memory usage: 5.8+ KB

In [5]:
df_hospitales.describe()

              ID       ALTURA
count  36.000000    36.000000
mean   18.500000  2074.055556
std    10.535654  1394.349453
min     1.000000    15.000000
25%     9.750000   924.750000
50%    18.500000  2041.000000
75%    27.250000  2776.250000
max    36.000000  5044.000000

In [6]:
df_hospitales.columns

Index(['WKT', 'ID', 'NOMBRE', 'NOM_MAP', 'OBJETO', 'CALLE', 'ALTURA',
       'DOM_NORMA', 'DOM_GEO', 'TELEFONO', 'GUARDIA', 'FAX', 'WEB',
       'COD_POSTAL', 'TIPO', 'TIPO_ESPEC', 'MOD_AT_1', 'MOD_AT_2',
       'DEPEND_ADM', 'DIRECTOR'],
      dtype='object')

In [7]:
df_hospitales.shape

(36, 20)

In [8]:
df_hospitales.head(5)

,WKT,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,POINT (-58.3775508488443 -34.6288473603881),1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,POINT (-58.4120700769456 -34.5941919726393),2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,POINT (-58.4027276547828 -34.5845283357505),4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,POINT (-58.3851559118889 -34.6394041316484),6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,POINT (-58.3913114406535 -34.6341535760002),7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

In [12]:
latitude_longitude = df_hospitales['WKT']
#print(latitude_longitude)
adress = df_hospitales['DOM_NORMA']
label = df_hospitales['NOMBRE']

In [15]:
info_imp_hospitales = {'latitud y longitud' : latitude_longitude,
                        'direccion': adress,
                        'nombre' : label}

In [16]:
df_hospitales2 = pd.DataFrame(info_imp_hospitales)

In [17]:
print(df_hospitales2)

                             latitud y longitud  \
0   POINT (-58.3775508488443 -34.6288473603881)
1   POINT (-58.4120700769456 -34.5941919726393)
2   POINT (-58.4027276547828 -34.5845283357505)
3   POINT (-58.3851559118889 -34.6394041316484)
4   POINT (-58.3913114406535 -34.6341535760002)
5   POINT (-58.4349433479819 -34.6084721257413)
6   POINT (-58.3758433488021 -34.6302112044495)
7   POINT (-58.3823284509488 -34.6357022351559)
8   POINT (-58.3821283746958 -34.6364350546569)
9   POINT (-58.3601201271455 -34.6388917320834)
10  POINT (-58.4409882382439 -34.5538963316473)
11   POINT (-58.4027506275377 -34.634856308415)
12  POINT (-58.4601855775528 -34.6054342750207)
13  POINT (-58.4276597542837 -34.6146348348429)
14  POINT (-58.4332484381295 -34.6070507603866)
15  POINT (-58.4323966950244 -34.6255031952483)
16  POINT (-58.3940641604746 -34.6227125075124)
17  POINT (-58.5021449222222 -34.6179817540591)
18  POINT (-58.3937269413225 -34.6375293258416)
19  POINT (-58.4752588459761 -34.5972098729151)
20  POINT (-58.4005134574423 -34.5847659581214)
21   POINT (-58.365985088719 -34.6283448581677)
22   POINT (-58.4068939142787 -34.581141710889)
23   POINT (-58.437981361705 -34.6089728538414)
24  POINT (-58.4695020363265 -34.6241704940114)
25  POINT (-58.4096107488155 -34.6176598438607)
26   POINT (-58.4710781593251 -34.565051956568)
27   POINT (-58.5110525000569 -34.599979524264)
28    POINT (-58.50761514092 -34.6253367952668)
29  POINT (-58.5156291936709 -34.6491867281064)
30  POINT (-58.4108602188291 -34.6431172591975)
31  POINT (-58.4710976282168 -34.5873917690227)
32   POINT (-58.4541167814714 -34.643894071866)
33  POINT (-58.4566428491103 -34.6718480140772)
34  POINT (-58.3918791813882 -34.6299453614404)
35  POINT (-58.3814293381891 -34.6419888014928)

                               direccion  \
0           MONTES DE OCA, MANUEL AV. 40
1                             GALLO 1330
2             SANCHEZ DE BUSTAMANTE 2529
3                          BRANDSEN 2570
4                       CASEROS AV. 2061
5                    DIAZ VELEZ AV. 4821
6            FINOCHIETTO ENRIQUE DR. 849
7               CARRILLO, RAMON, DR. 315
8               CARRILLO, RAMON, DR. 375
9          DON PEDRO DE MENDOZA AV. 1795
10                        ECHEVERRIA 955
11                 LUCA, ESTEBAN DE 2151
12               JUSTO, JUAN B. AV. 4151
13                              MUÑIZ 15
14          PATRICIAS ARGENTINAS AV. 150
15                 GOYENA, PEDRO AV. 369
16                     SAN JUAN AV. 2021
17                     SEGUROLA AV. 1949
18                        USPALLATA 2272
19                       WARNES AV. 2630
20            LAS HERAS GENERAL AV. 2670
21                      PI Y MARGALL 750
22                      CERVIÑO AV. 3356
23                   DIAZ VELEZ AV. 5044
24          ARANGUREN, JUAN F., DR. 2701
25                    URQUIZA, GRAL. 609
26                       MONROE AV. 3555
27                       NUEVA YORK 3952
28      CALDERON DE LA BARCA, PEDRO 1550
29                             PILAR 950
30        CHUTRO, PEDRO, PROF., DR. 3380
31     COMBATIENTES DE MALVINAS AV. 3002
32                       VARELA AV. 1301
33  FERNANDEZ DE LA CRUZ, F., GRAL. 4402
34             COMBATE DE LOS POZOS 1881
35                       SUAREZ AV. 2215

                                               nombre
0         HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE
1         HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ
2   HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...
3             HOSPITAL DE SALUD MENTAL BRAULIO MOYANO
4            HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO
5                    INSTITUTO DE ZOONOSIS L. PASTEUR
6   HOSPITAL DE REHABILITACION RESPIRATORIA MARIA ...
7            HOSPITAL INFANTO JUVENIL C. TOBAR GARCIA
8                HOSPITAL DE SALUD MENTAL J. T. BORDA
9   HOSPITAL DE ODONTOLOGIA INFANTIL DON BENITO QU...
10  INSTITUTO DE REHABILITACION PSICOFISICA (I.R.E...
11                 HOSPITAL MATERNO INFANTIL R. SARDA
12          HOSPITAL OFTALMOLOGICO DR. PEDRO LAGLEYZE
13               HOSPITAL DE ODONTOLOGIA  JOSE DUEÑAS
14        HOSPITAL MUNICIPAL DE ONCOLOGIA MARIE CURIE
15      HOSPITAL DE QUEMADOS DR. ARTURO UMBERTO ILLIA
16               HOSPITAL DE OFTALMOLOGIA SANTA LUCIA
17                HOSPITAL DE REHABILITACION M. ROCCA
18                   HOSPITAL DE INFECCIOSAS F. MUÑIZ
19  HOSPITAL DE EMERGENCIAS PSIQUIATRICAS TORCUATO...
20            HOSPITAL GENERAL DE AGUDOS B. RIVADAVIA
21          HOSPITAL GENERAL DE AGUDOS DR C. ARGERICH
22     HOSPITAL GENERAL DE AGUDOS DR. J. A. FERNANDEZ
23           HOSPITAL GENERAL DE AGUDOS DR. C. DURAND
24          HOSPITAL GENERAL DE AGUDOS DR. T. ALVAREZ
25       HOSPITAL GENERAL DE AGUDOS J. M. RAMOS MEJIA
26         HOSPITAL GENERAL DE AGUDOS DR. I. PIROVANO
27          HOSPITAL GENERAL DE AGUDOS A. ZUBIZARRETA
28      HOSPITAL GENERAL DE AGUDOS D. VELEZ SARSFIELD
29  HOSPITAL GENERAL DE AGUDOS DONACION F. SANTOJANNI
30             HOSPITAL GENERAL DE AGUDOS J. A. PENNA
31            HOSPITAL GENERAL DE AGUDOS DR. E. TORNU
32               HOSPITAL GENERAL DE AGUDOS P. PIÑERO
33                          HOSPITAL CECILIA GRIERSON
34                 HOSP. DE PEDIATRIA DR. J. GARRAHAN
35  TALLERES PROTEGIDOS DE REHABILITACION PSIQUIAT...

In [20]:
df_hospitales2.to_csv('Hospitales2.csv',sep=',',index=False)
#,columns=True,index=True)